(()=>{
let enabled=false,selected=null,records={},timer;
const dbReady=new Promise((resolve,reject)=>{const r=indexedDB.open('jackie-layout-editor',1);r.onupgradeneeded=()=>r.result.createObjectStore('draft');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
const panel=document.createElement('aside');panel.id='layout-editor';panel.innerHTML=`<button id="edit-toggle">编辑排版</button><div class="edit-controls" hidden><p>点击文字编辑；点击图片或占位区域调整</p><button id="edit-upload">插入 / 替换图片</button><input id="edit-file" type="file" accept="image/*" hidden><label>图片宽度 <input id="edit-width" type="range" min="20" max="150" value="100"></label><label>图片高度 <input id="edit-height" type="range" min="20" max="150" value="100"></label><label>水平位置 <input id="edit-x" type="range" min="0" max="100" value="50"></label><label>垂直位置 <input id="edit-y" type="range" min="0" max="100" value="50"></label><select id="edit-fit"><option value="cover">裁切填满</option><option value="contain">完整显示</option></select><button id="edit-export">导出编辑备份</button><button id="edit-import">导入编辑备份</button><input id="edit-json" type="file" accept="application/json" hidden><small id="edit-status">修改自动保存到此浏览器</small></div>`;document.body.append(panel);
const status=t=>panel.querySelector('#edit-status').textContent=t;
async function save(){try{const db=await dbReady;const tx=db.transaction('draft','readwrite');tx.objectStore('draft').put(records,'v8');tx.oncomplete=()=>status('已自动保存到此浏览器');tx.onerror=()=>status('保存失败，请导出编辑备份');}catch{status('保存失败，请导出编辑备份');}}
function schedule(){status('正在保存…');clearTimeout(timer);timer=setTimeout(save,250)}
function apply(el,r){if(r.text!==undefined){el.textContent=r.text;el.style.whiteSpace='pre-line'}if(r.image){let img=el.matches('img')?el:el.querySelector('img');if(!img){img=document.createElement('img');el.replaceChildren(img)}img.src=r.image;img.alt='自定义图片';}const img=el.matches('img')?el:el.querySelector('img');if(img){img.style.width=(r.width||100)+'%';img.style.height=(r.height||100)+'%';img.style.objectFit=r.fit||'cover';img.style.objectPosition=`${r.x??50}% ${r.y??50}%`;}}
window.prepareEditor=()=>{const groups=[[document.querySelector('main'),'main'],[document.querySelector('#detail-content'),'project-'+document.querySelector('#detail-content').dataset.projectIndex]];for(const [root,prefix] of groups){let n=0;root.querySelectorAll('img,.slot').forEach(el=>{if(el.matches('.slot')&&el.querySelector('img'))return;const id=el.dataset.editId||`${prefix}-image-${n}`;n++;el.dataset.editId=id;el.dataset.editKind='image';if(records[id])apply(el,records[id]);});n=0;root.querySelectorAll('h1,h2,h3,h4,p,small,figcaption,td,th,.awards li span,.awards li b,.skills-text,.prism-face strong,.author-name,.work-names button>span,.extra-cover-link>span').forEach(el=>{if(el.querySelector('img')||el.closest('#layout-editor'))return;const id=el.dataset.editId||`${prefix}-text-${n}`;n++;el.dataset.editId=id;el.dataset.editKind='text';el.contentEditable=enabled?'true':'false';if(records[id])apply(el,records[id]);});}};
panel.querySelector('#edit-toggle').onclick=()=>{enabled=!enabled;document.body.classList.toggle('editing-layout',enabled);panel.querySelector('.edit-controls').hidden=!enabled;panel.querySelector('#edit-toggle').textContent=enabled?'完成编辑':'编辑排版';document.querySelectorAll('[data-edit-kind="text"]').forEach(e=>e.contentEditable=enabled?'true':'false');};
document.addEventListener('click',e=>{if(!enabled||panel.contains(e.target))return;const el=e.target.closest('[data-edit-id]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();document.querySelector('.edit-selected')?.classList.remove('edit-selected');selected=el;el.classList.add('edit-selected');if(el.dataset.editKind==='text'){el.focus();updateTextTool();return}const r=records[el.dataset.editId]||{};['width','height','x','y'].forEach(k=>panel.querySelector('#edit-'+k).value=r[k]??(k==='width'||k==='height'?100:50));panel.querySelector('#edit-fit').value=r.fit||'cover';status('已选中图片，可替换或调整');},true);
document.addEventListener('input',e=>{const el=e.target.closest('[data-edit-kind="text"]');if(!enabled||!el)return;records[el.dataset.editId]={text:el.innerText};schedule()});
document.addEventListener('paste',e=>{if(!enabled||!e.target.closest('[contenteditable="true"]'))return;e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'))});
panel.querySelector('#edit-upload').onclick=()=>{if(!selected||selected.dataset.editKind!=='image'){status('请先点击要调整的图片或空白占位区域');return}panel.querySelector('#edit-file').click()};
panel.querySelector('#edit-file').onchange=async e=>{const file=e.target.files[0];if(!file||!selected)return;if(!file.type.startsWith('image/'))return;const target=selected;const reader=new FileReader();reader.onload=()=>{const id=target.dataset.editId;records[id]={...records[id],image:reader.result};apply(target,records[id]);schedule()};reader.readAsDataURL(file);e.target.value=''};
['width','height','x','y','fit'].forEach(k=>panel.querySelector('#edit-'+k).oninput=e=>{if(!selected||selected.dataset.editKind!=='image')return;const id=selected.dataset.editId;records[id]={...records[id],[k]:k==='fit'?e.target.value:Number(e.target.value)};apply(selected,records[id]);schedule()});
panel.querySelector('#edit-export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:8,records})],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Jackie-排版备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
panel.querySelector('#edit-import').onclick=()=>panel.querySelector('#edit-json').click();
panel.querySelector('#edit-json').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==8||!data.records)throw Error();for(const r of Object.values(data.records)){if(r.image&&!/^data:image\//.test(r.image))throw Error();}records=data.records;await save();window.prepareEditor();status('备份已导入')}catch{status('无法读取此备份，请选择本页导出的 JSON')}e.target.value=''};
const dialog=document.querySelector('#project-dialog');new MutationObserver(()=>{(dialog.open?dialog:document.body).append(panel)}).observe(dialog,{attributes:true,attributeFilter:['open']});
dbReady.then(db=>{const r=db.transaction('draft').objectStore('draft').get('v8');r.onsuccess=()=>{records=r.result||{};window.prepareEditor()}}).catch(()=>{status('浏览器存储不可用，请使用导出备份');window.prepareEditor()});
const tt=document.createElement('div');tt.className='text-tools';tt.innerHTML='<strong>文字工具（先点击文字）</strong><label>字体 <select data-t="font"><option value="inherit">跟随页面</option><option value="Chillax, sans-serif">Chillax</option><option value="Arial, sans-serif">Arial</option><option value="serif">衬线体</option></select></label><label>字号 <input data-t="size" type="range" min="10" max="120" value="16"><output>16px</output></label><label>字重 <select data-t="weight"><option value="400">常规</option><option value="500">中等</option><option value="700">粗体</option></select></label><label>颜色 <input data-t="color" type="color" value="#30372e"></label><label>行高 <input data-t="line" type="range" min="1" max="3" step=".1" value="1.5"></label><label>字距 <input data-t="spacing" type="range" min="-2" max="20" step=".5" value="0"></label><label>对齐 <select data-t="align"><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label>';panel.querySelector('.edit-controls').prepend(tt);
function updateTextTool(){if(!selected||selected.dataset.editKind!=='text')return;const id=selected.dataset.editId,r=records[id]||{};for(const k of ['font','size','weight','color','line','spacing','align']){const el=tt.querySelector(`[data-t="${k}"]`);if(!el)continue;el.value=r[k]??(k==='size'?16:k==='weight'?400:k==='line'?1.5:k==='color'?'#30372e':k==='font'?'inherit':k==='align'?'left':0)}tt.querySelector('output').textContent=tt.querySelector('[data-t="size"]').value+'px'}
tt.addEventListener('input',e=>{if(!selected||selected.dataset.editKind!=='text')return;const k=e.target.dataset.t;if(!k)return;const id=selected.dataset.editId,r=records[id]||{};r[k]=['size','weight','line','spacing'].includes(k)?Number(e.target.value):e.target.value;records[id]=r;selected.style[k==='font'?'fontFamily':k==='size'?'fontSize':k==='weight'?'fontWeight':k==='line'?'lineHeight':k==='spacing'?'letterSpacing':k==='align'?'textAlign':k]=k==='size'?r[k]+'px':k==='spacing'?r[k]+'px':r[k];if(k==='size')tt.querySelector('output').textContent=r[k]+'px';schedule()});
const oldFocus=document.addEventListener;
})();

